sudo: false
language: go
env:
- PROJECT="nrpe_exporter"
go:
- 1.9.x
- 1.x
go_import_path: github.com/prometheus/blackbox_exporter
script:
- make vet build
before_deploy:
- go get github.com/mitchellh/gox
- gox -os linux -output "./bin/{{.OS}}_{{.Arch}}/${PROJECT}"
- for i in ./bin/*; do cp "$i/${PROJECT}" . && tar -cvf "${PROJECT}-${TRAVIS_TAG//v/}.${i##*/}.tar.gz" $PROJECT LICENSE NOTICE VERSION blackbox.yml; done; rm "${PROJECT}"; done
deploy:
  provider: releases
  file_glob: true
  file: "*.tar.gz"
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: akYI0/vhoHg6U7aSCujK2rLQvnrN0jsozXEIiCnhUMBLfJKWPVVRCg39XrtfRbgPHK59PkJduzCzn3Rl8QozhZdoXaa6MsSKKt3lsVwiqEH768u6F76b1TEkqHO4ZVW7NXdhfOVyLNMkYnIUAhlmyowM/15Rb6M/kT2lpQ52lgTtSelAY+hSVLYbYPmemzPBWnVM9dCZ5QX+K7a6HQjvK/I0sf5/QnSDzKGppkSN/TXTCsaoj5AZF7ikWI4bglKrz45ioCK8XIDey6h4l4XneZAX2NnqJtG6tkCbaVAAJ8XjQsHlp5k7TmRu8p+IUaWCRDsOfNZeIsJ80JePCGDWNq+Qtx8SrNRPD7mr4w9D0MM66vyuraAKkpPgu3aVUDB/EJyeWrvY/kLpOyzAwzZtaY7k6M1k7VjRHLjnb7r37zWDbJ+hWPvHA1ocJwF8UP7OV9k3CAiOzN5M/Q/iadkRjQpmldpks0KRbeCOjvP8JIZ13JmWYZB3jE8JWJGXbtHOlWQ1ujhblTJB70g4w461+vvGmRTfeRz9n5cXo0kxjYaiS31NZs45ybwlsE6ENkhuu/rkEbKgv+J2wh5AVcxgvXQRI8Kc9i6U1IpiSOmNnHepYj4DTaSbBBqIJfVkF+vAnECTkENAVlKP9w0xup/3IOiW/CwVIoaKpd1de+yij2I=
